version: "3.9"

networks:
    budget:
        name: budget

services:
    %Host.ServerName%:
        container_name: %Host.ServerContainerName%
        image: budget/server:%Host.ContainerTag%
        ports: 
            - "%Host.ServerExternalPort%:443"
        environment:
          - ASPNETCORE_ENVIRONMENT=Production
          - ASPNETCORE_URLS=https://+:443
          - ASPNETCORE_Kestrel__Certificates__Default__Password=%Sec.DevCertPassword%
          - ASPNETCORE_Kestrel__Certificates__Default__Path=%Sec.DevCertPath%
        volumes:
          - %Sec.DevCertSharePath%:/https:ro
        networks:
            - budget
