// <auto-generated />
using System;
using BudgetServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BudgetServer.Migrations
{
    [DbContext(typeof(BudgetContext))]
    [Migration("20220526025816_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BudgetServer.Data.Models.TransactionCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TransactionCategoryGroupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TransactionCategoryGroupId");

                    b.ToTable("TransactionCategory", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mortgage",
                            TransactionCategoryGroupId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Water bill",
                            TransactionCategoryGroupId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Electric bill",
                            TransactionCategoryGroupId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Gas bill",
                            TransactionCategoryGroupId = 1
                        });
                });

            modelBuilder.Entity("BudgetServer.Data.Models.TransactionCategoryGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TransactionCategoryGroup", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Home"
                        });
                });

            modelBuilder.Entity("BudgetServer.Data.Models.TransactionEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(7,2)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Memo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TransactionCategoryId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("TransactionDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("TransactionCategoryId");

                    b.ToTable("TransactionEntry", (string)null);
                });

            modelBuilder.Entity("BudgetServer.Data.Models.TransactionCategory", b =>
                {
                    b.HasOne("BudgetServer.Data.Models.TransactionCategoryGroup", "TransactionCategoryGroup")
                        .WithMany("TransactionCategories")
                        .HasForeignKey("TransactionCategoryGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TransactionCategoryGroup");
                });

            modelBuilder.Entity("BudgetServer.Data.Models.TransactionEntry", b =>
                {
                    b.HasOne("BudgetServer.Data.Models.TransactionCategory", "TransactionCategory")
                        .WithMany()
                        .HasForeignKey("TransactionCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TransactionCategory");
                });

            modelBuilder.Entity("BudgetServer.Data.Models.TransactionCategoryGroup", b =>
                {
                    b.Navigation("TransactionCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
